// Paint catalogues per medium. Hexes are approximate masstone colours.
export const CATALOGUES = {
  oil: [
    { id: 'wn-winsor-lemon',  brand: 'Winsor & Newton', name: 'Winsor Lemon',            code: 'PY175', hex: '#F4E01F' },
    { id: 'wn-winsor-yellow', brand: 'Winsor & Newton', name: 'Winsor Yellow',           code: 'PY97',  hex: '#F4E438' },
    { id: 'wn-cad-yellow',    brand: 'Winsor & Newton', name: 'Cadmium Yellow',          code: 'PY35',  hex: '#F6BE00' },
    { id: 'wn-cad-orange',    brand: 'Winsor & Newton', name: 'Cadmium Orange',          code: 'PO20',  hex: '#E8722A' },
    { id: 'wn-cad-red',       brand: 'Winsor & Newton', name: 'Cadmium Red',             code: 'PR108', hex: '#C42E2B' },
    { id: 'wn-perm-rose',     brand: 'Winsor & Newton', name: 'Permanent Rose',          code: 'PV19',  hex: '#C4266E' },
    { id: 'wn-aliz',          brand: 'Winsor & Newton', name: 'Alizarin Crimson',        code: 'PR83',  hex: '#8E1F33' },
    { id: 'wn-winsor-violet', brand: 'Winsor & Newton', name: 'Winsor Violet',           code: 'PV23',  hex: '#472B7A' },
    { id: 'wn-ultramarine',   brand: 'Winsor & Newton', name: 'French Ultramarine',      code: 'PB29',  hex: '#1B2E6F' },
    { id: 'wn-winsor-blue',   brand: 'Winsor & Newton', name: 'Winsor Blue (GS)',        code: 'PB15:3',hex: '#1D5A80' },
    { id: 'wn-cerulean',      brand: 'Winsor & Newton', name: 'Cerulean Blue',           code: 'PB35',  hex: '#2A6FA8' },
    { id: 'wn-winsor-green',  brand: 'Winsor & Newton', name: 'Winsor Green (BS)',       code: 'PG7',   hex: '#2E5D3A' },
    { id: 'wn-viridian',      brand: 'Winsor & Newton', name: 'Viridian',                code: 'PG18',  hex: '#2C8F78' },
    { id: 'wn-sap-green',     brand: 'Winsor & Newton', name: 'Sap Green',               code: 'PG36',  hex: '#5A6E28' },
    { id: 'wn-yellow-ochre',  brand: 'Winsor & Newton', name: 'Yellow Ochre',            code: 'PY43',  hex: '#C8912B' },
    { id: 'wn-raw-sienna',    brand: 'Winsor & Newton', name: 'Raw Sienna',              code: 'PBr7',  hex: '#B07A33' },
    { id: 'wn-burnt-sienna',  brand: 'Winsor & Newton', name: 'Burnt Sienna',            code: 'PR101', hex: '#8C3B24' },
    { id: 'wn-light-red',     brand: 'Winsor & Newton', name: 'Light Red',               code: 'PR102', hex: '#B23A28' },
    { id: 'wn-burnt-umber',   brand: 'Winsor & Newton', name: 'Burnt Umber',             code: 'PBr7',  hex: '#4A3222' },
    { id: 'wn-raw-umber',     brand: 'Winsor & Newton', name: 'Raw Umber',               code: 'PBr7',  hex: '#5C4B32' },
    { id: 'wn-titanium',      brand: 'Winsor & Newton', name: 'Titanium White',          code: 'PW6',   hex: '#F8F7F2', white: true },
    { id: 'wn-ivory-black',   brand: 'Winsor & Newton', name: 'Ivory Black',             code: 'PBk9',  hex: '#26211C' },
    { id: 'mh-titanium',      brand: 'Michael Harding', name: 'Titanium White No.1',     code: 'PW6',   hex: '#F9F8F3', white: true },
    { id: 'mh-bright-green',  brand: 'Michael Harding', name: 'Bright Green Lake',       code: 'PG7·PY3', hex: '#3E8A3C' },
    { id: 'mh-magenta',       brand: 'Michael Harding', name: 'Magenta',                 code: 'PR122', hex: '#B03580' },
    { id: 'oh-ruby',          brand: 'Old Holland',     name: 'Ruby Lake',               code: 'PV19',  hex: '#C0256B' },
    { id: 'oh-manganese',     brand: 'Old Holland',     name: 'Manganese Violet',        code: 'PV16',  hex: '#5B3A8E' },
    { id: 'oh-viridian-deep', brand: 'Old Holland',     name: 'Viridian Green Deep',     code: 'PG18',  hex: '#27866F' },
    { id: 'oh-titanium',      brand: 'Old Holland',     name: 'Titanium White',          code: 'PW6',   hex: '#F9F8F4', white: true },
    { id: 'oh-cad-yellow',    brand: 'Old Holland',     name: 'Cadmium Yellow Medium',   code: 'PY35',  hex: '#F3B90A' },
    { id: 'oh-cad-red-scar',  brand: 'Old Holland',     name: 'Cadmium Red Scarlet',     code: 'PR108', hex: '#CE3420' },
    { id: 'oh-cobalt-blue',   brand: 'Old Holland',     name: 'Cobalt Blue',             code: 'PB28',  hex: '#2A4F9E' },
    { id: 'oh-yellow-ochre',  brand: 'Old Holland',     name: 'Yellow Ochre Light',      code: 'PY43',  hex: '#C79233' },
    { id: 'oh-burnt-sienna',  brand: 'Old Holland',     name: 'Burnt Sienna',            code: 'PBr7',  hex: '#8C4126' },
    { id: 'mh-cad-yellow',    brand: 'Michael Harding', name: 'Cadmium Yellow',          code: 'PY35',  hex: '#F4BB00' },
    { id: 'mh-cad-red',       brand: 'Michael Harding', name: 'Cadmium Red',             code: 'PR108', hex: '#C52E2A' },
    { id: 'mh-ultramarine',   brand: 'Michael Harding', name: 'Ultramarine Blue',        code: 'PB29',  hex: '#1E2F78' },
    { id: 'mh-phthalo-blue',  brand: 'Michael Harding', name: 'Phthalocyanine Blue',     code: 'PB15:3',hex: '#1B5583' },
    { id: 'mh-yellow-ochre',  brand: 'Michael Harding', name: 'Yellow Ochre',            code: 'PY43',  hex: '#C08A2E' },
    { id: 'mh-burnt-sienna',  brand: 'Michael Harding', name: 'Burnt Sienna',            code: 'PBr7',  hex: '#8C3E22' },
    { id: 'gb-titanium',      brand: 'Gamblin',         name: 'Titanium White',          code: 'PW6',   hex: '#F8F8F4', white: true },
    { id: 'gb-titanium-zinc', brand: 'Gamblin',         name: 'Titanium Zinc White',     code: 'PW6·PW4', hex: '#F9F9F5', white: true },
    { id: 'gb-aliz-crimson',  brand: 'Gamblin',         name: 'Alizarin Crimson',        code: 'PR83',  hex: '#8B1F33' },
    { id: 'gb-indian-yellow', brand: 'Gamblin',         name: 'Indian Yellow',           code: 'PY110', hex: '#D98A0E' },
    { id: 'gb-nickel-titanate', brand: 'Gamblin',       name: 'Nickel Titanate Yellow',  code: 'PY53',  hex: '#E9DD92' },
    { id: 'gb-manganese-hue', brand: 'Gamblin',         name: 'Manganese Blue Hue',      code: 'PB15',  hex: '#2E90C0' },
    { id: 'gb-cad-lemon',     brand: 'Gamblin',         name: 'Cadmium Lemon',           code: 'PY35',  hex: '#F5E027' },
    { id: 'gb-cad-yellow',    brand: 'Gamblin',         name: 'Cadmium Yellow Medium',   code: 'PY35',  hex: '#F2AF0D' },
    { id: 'gb-cad-orange',    brand: 'Gamblin',         name: 'Cadmium Orange',          code: 'PO20',  hex: '#E97C1E' },
    { id: 'gb-cad-red',       brand: 'Gamblin',         name: 'Cadmium Red Medium',      code: 'PR108', hex: '#C22A24' },
    { id: 'gb-aliz-perm',     brand: 'Gamblin',         name: 'Alizarin Permanent',      code: 'PR177', hex: '#8E2138' },
    { id: 'gb-quin-red',      brand: 'Gamblin',         name: 'Quinacridone Red',        code: 'PV19',  hex: '#C3306A' },
    { id: 'gb-diox-purple',   brand: 'Gamblin',         name: 'Dioxazine Purple',        code: 'PV23',  hex: '#46256E' },
    { id: 'gb-ultramarine',   brand: 'Gamblin',         name: 'Ultramarine Blue',        code: 'PB29',  hex: '#20307A' },
    { id: 'gb-phthalo-blue',  brand: 'Gamblin',         name: 'Phthalo Blue',            code: 'PB15:3',hex: '#1A5586' },
    { id: 'gb-phthalo-green', brand: 'Gamblin',         name: 'Phthalo Green',           code: 'PG7',   hex: '#1F6B52' },
    { id: 'gb-yellow-ochre',  brand: 'Gamblin',         name: 'Yellow Ochre',            code: 'PY43',  hex: '#C6912F' },
    { id: 'gb-burnt-sienna',  brand: 'Gamblin',         name: 'Burnt Sienna',            code: 'PBr7',  hex: '#8A3D26' },
    { id: 'gb-ivory-black',   brand: 'Gamblin',         name: 'Ivory Black',             code: 'PBk9',  hex: '#26211C' },
    { id: 'wb-titanium',      brand: 'Williamsburg Handmade Oil Paints', name: 'Titanium White',          code: 'PW6',   hex: '#F8F8F3', white: true },
    { id: 'wb-cad-lemon',     brand: 'Williamsburg Handmade Oil Paints', name: 'Cadmium Lemon',           code: 'PY35',  hex: '#F2DE1D' },
    { id: 'wb-cad-yellow',    brand: 'Williamsburg Handmade Oil Paints', name: 'Cadmium Yellow Medium',   code: 'PY35',  hex: '#F2B70B' },
    { id: 'wb-fanchon-red',   brand: 'Williamsburg Handmade Oil Paints', name: 'Fanchon Red',             code: 'PR254', hex: '#C2271B' },
    { id: 'wb-perm-crimson',  brand: 'Williamsburg Handmade Oil Paints', name: 'Permanent Crimson',       code: 'PR264', hex: '#A01E30' },
    { id: 'wb-provence',      brand: 'Williamsburg Handmade Oil Paints', name: 'Provence Violet Bluish',  code: 'PV23',  hex: '#4B2C79' },
    { id: 'wb-ultramarine',   brand: 'Williamsburg Handmade Oil Paints', name: 'French Ultramarine Blue', code: 'PB29',  hex: '#202F7C' },
    { id: 'wb-phthalo-green', brand: 'Williamsburg Handmade Oil Paints', name: 'Phthalo Green',           code: 'PG7',   hex: '#1E6A50' },
    { id: 'wb-raw-sienna',    brand: 'Williamsburg Handmade Oil Paints', name: 'Italian Raw Sienna',      code: 'PBr7',  hex: '#B27C35' },
    { id: 'wb-burnt-umber',   brand: 'Williamsburg Handmade Oil Paints', name: 'Burnt Umber',             code: 'PBr7',  hex: '#4A3323' },
    { id: 'mg-titanium',      brand: 'M. Graham & Co',  name: 'Titanium White',          code: 'PW6',   hex: '#F8F8F4', white: true },
    { id: 'mg-azo-yellow',    brand: 'M. Graham & Co',  name: 'Azo Yellow',              code: 'PY151', hex: '#F3CE16' },
    { id: 'mg-cad-yellow',    brand: 'M. Graham & Co',  name: 'Cadmium Yellow',          code: 'PY35',  hex: '#F4BC05' },
    { id: 'mg-cad-red',       brand: 'M. Graham & Co',  name: 'Cadmium Red',             code: 'PR108', hex: '#C42B25' },
    { id: 'mg-quin-rose',     brand: 'M. Graham & Co',  name: 'Quinacridone Rose',       code: 'PV19',  hex: '#C13A72' },
    { id: 'mg-diox-purple',   brand: 'M. Graham & Co',  name: 'Dioxazine Purple',        code: 'PV23',  hex: '#452867' },
    { id: 'mg-ultramarine',   brand: 'M. Graham & Co',  name: 'Ultramarine Blue',        code: 'PB29',  hex: '#22317E' },
    { id: 'mg-phthalo-blue',  brand: 'M. Graham & Co',  name: 'Phthalocyanine Blue',     code: 'PB15',  hex: '#1A5486' },
    { id: 'mg-phthalo-green', brand: 'M. Graham & Co',  name: 'Phthalocyanine Green',    code: 'PG7',   hex: '#1F6C53' },
    { id: 'mg-burnt-sienna',  brand: 'M. Graham & Co',  name: 'Burnt Sienna',            code: 'PBr7',  hex: '#8B3F27' },
    // Winton (W&N's student line) — the 19 colours of the Winton Oil Colour Set
    // 20x12ml, which is also the default starting shelf for oils (see below).
    { id: 'winton-titanium',        brand: 'Winsor & Newton Winton', name: 'Titanium White',       code: 'PW6',      hex: '#F8F8F3', white: true },
    { id: 'winton-cad-lemon-hue',   brand: 'Winsor & Newton Winton', name: 'Cadmium Lemon Hue',    code: 'PY3',      hex: '#F1E135' },
    { id: 'winton-chrome-yellow',   brand: 'Winsor & Newton Winton', name: 'Chrome Yellow Hue',    code: 'PY65',     hex: '#F2BD1C' },
    { id: 'winton-cad-orange-hue',  brand: 'Winsor & Newton Winton', name: 'Cadmium Orange Hue',   code: 'PO73',     hex: '#E8761F' },
    { id: 'winton-scarlet-lake',    brand: 'Winsor & Newton Winton', name: 'Scarlet Lake',         code: 'PR188',    hex: '#CD3327' },
    { id: 'winton-cad-red-deep',    brand: 'Winsor & Newton Winton', name: 'Cadmium Red Deep Hue', code: 'PR170',    hex: '#9E2A24' },
    { id: 'winton-perm-rose',       brand: 'Winsor & Newton Winton', name: 'Permanent Rose',       code: 'PV19',     hex: '#C4266E' },
    { id: 'winton-magenta',         brand: 'Winsor & Newton Winton', name: 'Magenta',              code: 'PR122',    hex: '#AE3579' },
    { id: 'winton-cobalt-violet',   brand: 'Winsor & Newton Winton', name: 'Cobalt Violet Hue',    code: 'PV23·PW6', hex: '#7E4E9C' },
    { id: 'winton-phthalo-blue',    brand: 'Winsor & Newton Winton', name: 'Phthalo Blue',         code: 'PB15',     hex: '#1D5884' },
    { id: 'winton-ultramarine',     brand: 'Winsor & Newton Winton', name: 'French Ultramarine',   code: 'PB29',     hex: '#1F2F73' },
    { id: 'winton-cerulean-hue',    brand: 'Winsor & Newton Winton', name: 'Cerulean Blue Hue',    code: 'PB15:3',   hex: '#3E7FB1' },
    { id: 'winton-emerald',         brand: 'Winsor & Newton Winton', name: 'Emerald Green',        code: 'PG36',     hex: '#3FA466' },
    { id: 'winton-viridian-hue',    brand: 'Winsor & Newton Winton', name: 'Viridian Hue',         code: 'PG7',      hex: '#2C8A72' },
    { id: 'winton-sap-green',       brand: 'Winsor & Newton Winton', name: 'Sap Green',            code: 'PG7·PY83', hex: '#5A6E28' },
    { id: 'winton-pale-rose-blush', brand: 'Winsor & Newton Winton', name: 'Pale Rose Blush',      code: 'PR101·PW6',hex: '#EBC8BE' },
    { id: 'winton-burnt-sienna',    brand: 'Winsor & Newton Winton', name: 'Burnt Sienna',         code: 'PR101',    hex: '#8C3B24' },
    { id: 'winton-vandyke-brown',   brand: 'Winsor & Newton Winton', name: 'Vandyke Brown',        code: 'PBr7',     hex: '#453427' },
    { id: 'winton-lamp-black',      brand: 'Winsor & Newton Winton', name: 'Lamp Black',           code: 'PBk6',     hex: '#26241F' }
  ],
  acrylic: [
    { id: 'lq-yellow-light',  brand: 'Liquitex', name: 'Yellow Light Hansa',      code: 'PY3',   hex: '#F7E23B' },
    { id: 'lq-cad-yellow',    brand: 'Liquitex', name: 'Cadmium Yellow Medium',   code: 'PY35',  hex: '#F5BD02' },
    { id: 'lq-cad-orange',    brand: 'Liquitex', name: 'Cadmium Orange',          code: 'PO20',  hex: '#E67420' },
    { id: 'lq-cad-red',       brand: 'Liquitex', name: 'Cadmium Red Medium',      code: 'PR108', hex: '#C6302B' },
    { id: 'lq-quin-magenta',  brand: 'Liquitex', name: 'Quinacridone Magenta',    code: 'PR122', hex: '#A93A77' },
    { id: 'lq-diox-purple',   brand: 'Liquitex', name: 'Dioxazine Purple',        code: 'PV23',  hex: '#46256E' },
    { id: 'lq-ultramarine',   brand: 'Liquitex', name: 'Ultramarine Blue',        code: 'PB29',  hex: '#23357C' },
    { id: 'lq-phthalo-blue',  brand: 'Liquitex', name: 'Phthalo Blue (GS)',       code: 'PB15:3',hex: '#1A5B8C' },
    { id: 'lq-phthalo-green', brand: 'Liquitex', name: 'Phthalo Green',           code: 'PG7',   hex: '#1F6B52' },
    { id: 'lq-green-light',   brand: 'Liquitex', name: 'Light Green Permanent',   code: 'PY3·PG7', hex: '#5EA345' },
    { id: 'lq-yellow-oxide',  brand: 'Liquitex', name: 'Yellow Oxide',            code: 'PY42',  hex: '#C08F2E' },
    { id: 'lq-burnt-sienna',  brand: 'Liquitex', name: 'Burnt Sienna',            code: 'PBr7',  hex: '#8A3D26' },
    { id: 'lq-burnt-umber',   brand: 'Liquitex', name: 'Burnt Umber',             code: 'PBr7',  hex: '#4C3524' },
    { id: 'lq-titanium',      brand: 'Liquitex', name: 'Titanium White',          code: 'PW6',   hex: '#F8F8F3', white: true },
    { id: 'lq-mars-black',    brand: 'Liquitex', name: 'Mars Black',              code: 'PBk11', hex: '#24211E' },
    // Specialty & fluorescent — true fluorescents are essentially an acrylic-only
    // medium (dye-based, don't hold up in oil); these give the recipe engine real
    // high-chroma options for neon targets that no traditional pigment can reach.
    { id: 'golden-fluor-yellow', brand: 'Golden', name: 'Fluorescent Yellow-Green', code: 'Fluorescent', hex: '#E7FA1E', special: true },
    { id: 'golden-fluor-green',  brand: 'Golden', name: 'Fluorescent Green',        code: 'Fluorescent', hex: '#1EFA6E', special: true },
    { id: 'golden-fluor-blue',   brand: 'Golden', name: 'Fluorescent Blue',         code: 'Fluorescent', hex: '#1FA8FF', special: true },
    { id: 'golden-fluor-pink',   brand: 'Golden', name: 'Fluorescent Pink',         code: 'Fluorescent', hex: '#FF2D8A', special: true },
    { id: 'golden-fluor-orange', brand: 'Golden', name: 'Fluorescent Orange',       code: 'Fluorescent', hex: '#FF6A1A', special: true }
  ],
  watercolour: [
    { id: 'wc-winsor-lemon',  brand: 'Winsor & Newton', name: 'Winsor Lemon',        code: 'PY175', hex: '#F2E13C' },
    { id: 'wc-transp-yellow', brand: 'Winsor & Newton', name: 'Transparent Yellow',  code: 'PY150', hex: '#E8B71E' },
    { id: 'wc-cad-yellow',    brand: 'Winsor & Newton', name: 'Cadmium Yellow',      code: 'PY35',  hex: '#F3BC1E' },
    { id: 'wc-scarlet',       brand: 'Winsor & Newton', name: 'Scarlet Lake',        code: 'PR188', hex: '#CE3A2E' },
    { id: 'wc-perm-rose',     brand: 'Winsor & Newton', name: 'Permanent Rose',      code: 'PV19',  hex: '#C64B79' },
    { id: 'wc-aliz',          brand: 'Winsor & Newton', name: 'Alizarin Crimson',    code: 'PR83',  hex: '#97263F' },
    { id: 'wc-winsor-violet', brand: 'Winsor & Newton', name: 'Winsor Violet',       code: 'PV23',  hex: '#5A3E85' },
    { id: 'wc-ultramarine',   brand: 'Winsor & Newton', name: 'French Ultramarine',  code: 'PB29',  hex: '#2A3F8F' },
    { id: 'wc-cerulean',      brand: 'Winsor & Newton', name: 'Cerulean Blue',       code: 'PB35',  hex: '#3577A8' },
    { id: 'wc-winsor-green',  brand: 'Winsor & Newton', name: 'Winsor Green (BS)',   code: 'PG7',   hex: '#2D7057' },
    { id: 'wc-sap-green',     brand: 'Winsor & Newton', name: 'Sap Green',           code: 'PG36',  hex: '#6B7A2E' },
    { id: 'wc-yellow-ochre',  brand: 'Winsor & Newton', name: 'Yellow Ochre',        code: 'PY43',  hex: '#C79939' },
    { id: 'wc-burnt-sienna',  brand: 'Winsor & Newton', name: 'Burnt Sienna',        code: 'PR101', hex: '#99502C' },
    { id: 'wc-burnt-umber',   brand: 'Winsor & Newton', name: 'Burnt Umber',         code: 'PBr7',  hex: '#5C4632' },
    { id: 'wc-neutral-tint',  brand: 'Winsor & Newton', name: 'Neutral Tint',        code: 'PBk6·PB15', hex: '#3C3A44' },
    { id: 'water',            brand: '',                name: 'water',               code: '',      hex: '#FDFCF8', water: true }
  ]
};

export const DEFAULT_INVENTORY = {
  // Oils start with the Winton Oil Colour Set 20x12ml
  // (winsornewton.com/en-ca/collections/oil-sets/products/winton-oil-colour-set-20x12ml)
  oil: [
    'winton-titanium', 'winton-cad-lemon-hue', 'winton-chrome-yellow',
    'winton-cad-orange-hue', 'winton-scarlet-lake', 'winton-cad-red-deep',
    'winton-perm-rose', 'winton-magenta', 'winton-cobalt-violet',
    'winton-phthalo-blue', 'winton-ultramarine', 'winton-cerulean-hue',
    'winton-emerald', 'winton-viridian-hue', 'winton-sap-green',
    'winton-pale-rose-blush', 'winton-burnt-sienna', 'winton-vandyke-brown',
    'winton-lamp-black'
  ],
  acrylic: [
    'lq-cad-yellow', 'lq-cad-red', 'lq-ultramarine', 'lq-phthalo-green',
    'lq-yellow-oxide', 'lq-burnt-umber', 'lq-titanium', 'lq-mars-black'
  ],
  watercolour: [
    'wc-winsor-lemon', 'wc-cad-yellow', 'wc-scarlet', 'wc-ultramarine',
    'wc-winsor-green', 'wc-yellow-ochre', 'wc-burnt-sienna', 'wc-burnt-umber',
    'wc-neutral-tint', 'water'
  ]
};

export const MEDIUM_LABELS = { oil: 'Oil', acrylic: 'Acrylic', watercolour: 'Watercolour' };
